# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqjMBunbp3BiDr5uWLdWnRodtlc6Ofz3
"""

import streamlit as st
from convert_sap_to_template import convert_sap_to_template

st.title("SAP → Template Converter")
st.write("Upload file SAP để chuyển sang format chuẩn.")

uploaded_file = st.file_uploader("Upload file Excel", type=["xlsx"])

if uploaded_file:
    st.success("File đã upload thành công!")

    if st.button("Convert File"):
        try:
            buffer, filename = convert_sap_to_template(uploaded_file)
            st.success("Convert thành công!")

            st.download_button(
                label="⬇️ Download File Kết Quả",
                data=buffer,
                file_name=filename,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
        except Exception as e:
            st.error(f"Lỗi: {e}")