# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqjMBunbp3BiDr5uWLdWnRodtlc6Ofz3
"""

import streamlit as st
from convert_sap_to_template import convert_sap_to_template

# ===== CUSTOM CSS =====
def local_css():
    css = """
    <style>
        /* === BACKGROUND WITH LEAVES === */
        body {
            background-color: #f3f9f4 !important;
        }
        .stApp {
            background-image: url('https://i.imgur.com/35qKX0R.png');  /* light leaf texture */
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }

        /* Floating leaf animation */
        @keyframes leafFloat {
            0% { transform: translateY(0px) rotate(0deg); opacity: 0.6; }
            50% { transform: translateY(25px) rotate(10deg); opacity: 0.9; }
            100% { transform: translateY(0px) rotate(0deg); opacity: 0.6; }
        }

        .leaf {
            position: fixed;
            top: 15%;
            right: 10%;
            width: 85px;
            opacity: 0.7;
            animation: leafFloat 6s ease-in-out infinite;
            z-index: -1;
        }

        .title {
            font-size: 32px !important;
            font-weight: 800 !important;
            color: #1c7c38;
            padding-bottom: 5px;
        }
        .authorized {
            font-size: 14px !important;
            color: #4c6b57;
            margin-bottom: 25px;
            font-style: italic;
        }
        .card {
            padding: 25px;
            border-radius: 12px;
            background-color: rgba(255,255,255,0.9);
            box-shadow: 0px 2px 10px rgba(76, 175, 80, 0.25);
            margin-bottom: 20px;
            backdrop-filter: blur(4px);
        }
        .footer {
            text-align: center;
            margin-top: 35px;
            font-size: 12px;
            color: #789d7c;
        }

        /* Button theming */
        .stButton>button {
            background-color: #34a853;
            color: white;
            border-radius: 8px;
            height: 45px;
            border: none;
            font-size: 16px;
            font-weight: 600;
        }
        .stButton>button:hover {
            background-color: #2d8a46;
        }
    </style>

    <!-- Floating decorative leaf -->
    <img src="https://i.imgur.com/2y8e9cG.png" class="leaf">
    """
    st.markdown(css, unsafe_allow_html=True)

local_css()

# ========= TITLE & HEADER ==========
st.markdown('<div class="title">SAP to Standard Template Converter</div>', unsafe_allow_html=True)
st.markdown('<div class="authorized">Authorized by Ngo Danh Thai ® — Sales Operation Data Executive, MPS</div>', unsafe_allow_html=True)

# ========= MAIN LAYOUT ==========
col1, col2 = st.columns([1.2, 1])

with col1:
    st.markdown('<div class="card">', unsafe_allow_html=True)

    st.subheader("📤 Upload SAP File")
    st.write("Upload the SAP Excel file (.xlsx) to convert it into the standardized template format.")

    uploaded_file = st.file_uploader("Choose SAP File", type=["xlsx"])

    convert_btn = st.button("Convert File", use_container_width=True)

    st.markdown('</div>', unsafe_allow_html=True)

# ===== OUTPUT CARD =====
with col2:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.subheader("📥 Output File")

    if convert_btn:
        if uploaded_file:
            with st.spinner("Processing file…"):
                try:
                    buffer, filename = convert_sap_to_template(uploaded_file)
                    st.success("✔ Conversion completed successfully!")

                    st.download_button(
                        label="Download File",
                        data=buffer,
                        file_name=filename,
                        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        use_container_width=True
                    )

                except Exception as e:
                    st.error(f"❌ Error: {e}")
        else:
            st.warning("⚠ Please upload a file before converting.")

    st.markdown('</div>', unsafe_allow_html=True)

# ========= FOOTER ==========
st.markdown(
    '<div class="footer">© 2025 MPS Operations Data System — All rights reserved.</div>',
    unsafe_allow_html=True
)