# -*- coding: utf-8 -*-
"""convert_sap_to_template

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BmLOuuB1ZFF21jvDUfshkU1YtHRMsIWr
"""

import pandas as pd
from io import BytesIO

def convert_sap_to_template(uploaded_file):
    df = pd.read_excel(uploaded_file, header=None)

    delivery_number = df.iloc[0, 5]   # F1
    due_date_raw = df.iloc[0, 12]     # M1
    customer_code = df.iloc[0, 18]    # S1
    receiver_name = df.iloc[0, 14]    # O1

    # Normalize date
    issued_date = pd.to_datetime(due_date_raw, errors="coerce").strftime("%d/%m/%Y")
    due_date = issued_date

    issued_date_clean = issued_date.replace("/", "-")
    receiver_name_clean = str(receiver_name).replace("/", "-").replace("\\", "-")

    product_rows = []
    row = 1

    while True:
        product_code = str(df.iloc[row, 1]).strip()
        if not product_code.startswith("10000"):
            break

        quantity = df.iloc[row, 4]
        batch_number = df.iloc[row, 5]

        product_rows.append((product_code, quantity, batch_number))
        row += 1

    output = pd.DataFrame(product_rows, columns=["ProductCode", "Quantity", "BatchNumber"])
    output["DeliveryNumber"] = delivery_number
    output["IssuedDate"] = issued_date
    output["DueDate"] = due_date
    output["CustomerCode"] = customer_code
    output["DeliveryAddress"] = ""
    output["Remark"] = ""
    output["Purpose"] = "SALE"

    output = output[[
        "DeliveryNumber", "IssuedDate", "DueDate", "CustomerCode",
        "DeliveryAddress", "Remark", "ProductCode", "Quantity",
        "BatchNumber", "Purpose"
    ]]

    # Trả về file dạng bytes để Streamlit có thể download
    buffer = BytesIO()
    output.to_excel(buffer, index=False)
    buffer.seek(0)

    filename = f"{issued_date_clean}_{receiver_name_clean}.xlsx"
    return buffer, filename